### ISSUE TITLE
Repeated renames show up in log

### ISSUE THREAD

**Issue by pitaj** [NodeBB/nodebb-plugin-global-chat#7]
https://community.nodebb.org/topic/14396/v1-13-0-and-global-chat-plugin

**Comment by arranka** [comment]
![image](https://user-images.githubusercontent.com/30248115/70294341-e832ed00-17c1-11ea-9dfc-b211b32c54dd.png)
follow with the infinite guest, nobody ends, the chat became unusable

**Comment by pitaj** [comment]
Please stop spamming your issue all over the place. We get it. That fact that I created this issue means we know about it.

**Comment by pitaj** [comment]
I can't reproduce this. I have no idea how this is happening.

**Comment by barisusakli** [comment]
@arranka can you check your browsers network tab to see if there are rename requests being sent. You will have to check the websocket section under network tab.

**Comment by fgallese** [comment]
I originally reported this on nodebb community forum.
In our forum we put some css to not display this messages, and this helped but we still where getting the notification in the notifications icon.
We ended up disabling the plugin, this means that new users are not being added to the big global chat, but at least the chat didn't disappear.

Anyway, today when I get home I'll enable this plugin again and let you know if the issue is still there and provide you with any further info that you may need to debug it.

Thank you for your tiime looking into this.
